### ISSUE TITLE
How to add an external link in the figure tag

### ISSUE THREAD

**Issue by Le-future** [dimsemenov/PhotoSwipe#1019]
Hello guys,

As said in the title, I would like to add an external link in the html structure (see "FOR EXAMPLE HERE") : 

```
<div class="my-gallery" itemscope itemtype="http://schema.org/ImageGallery">

    <figure itemprop="associatedMedia" itemscope itemtype="http://schema.org/ImageObject">
        <a href="large-image.jpg" itemprop="contentUrl" data-size="600x400">
            <img src="small-image.jpg" itemprop="thumbnail" alt="Image description" />
        </a>
        <figcaption itemprop="caption description"> FOR EXAMPLE HERE </figcaption>
    </figure>

    <figure itemprop="associatedMedia" itemscope itemtype="http://schema.org/ImageObject">
        <a href="large-image.jpg" itemprop="contentUrl" data-size="600x400">
            <img src="small-image.jpg" itemprop="thumbnail" alt="Image description" />
        </a>
        <figcaption itemprop="caption description">Image caption</figcaption>
    </figure>


</div>
```

If I do this, the link open automatically the gallery but doesn't care about the href="" used.

Thanks per advance

**Comment by mjau-mjau** [comment]
Apologies for not testing myself, but I use a custom process for building the Photoswipe slides object. What happens if you just add the link directly to the figcaption? I am not 100% sure what you mean "but doesn't care about href used" ...

```html
<figcaption itemprop="caption description"><a href="https://disney.com">LINK</a></figcaption>
```

I assume you are using the sample code for building the slides object, in which case the title is populated with this:

```javascript
if(figureEl.children.length > 1) {
  // <figcaption> content
  item.title = figureEl.children[1].innerHTML; 
}
```

It should be copying the inner content, including the anchor tag, into the title property. I would like to know if it doesn't work because A) It doesn't copy the tag, or B) The anchor tag is somehow blocked by Photoswipe, in which case, there are ways to exclude it from being blocked.

**Comment by Le-future** [comment]
Hello!

Sorry for my delayed response!

What I mean is when I add a link inside the figcaption, if I click on it, nothing happens except the gallery launching. Photoswipe seems to block the external link. But when the gallery is opened, if I click below the picture on the external link, it's opening correctly.

Thanks a lot for your help 😉

**Comment by mjau-mjau** [comment]
If I could see a real link, and the actual code you are using, I could help. I can't help with screenshots of links that don't work.

**Comment by Le-future** [comment]
Hey!

Thanks again for your help, here is a direct link : http://noisacco.com/testps/index.html

Hope you will be able to help me

**Comment by Le-future** [comment]
I'm trying for more than 3 hours now to find out what's wrong but I can't find it...

**Comment by mjau-mjau** [comment]
This behavior is easily explained: You have added your CLICK event to `<figure>` child elements of your main `.my-gallery` element. The click event will therefore apply *anywhere* on the figure, including the text below the images ... This also means that the javascript click event applied to the entire `<figure>` element, will prevent `<a>` anchor tags inside the figure from working.

Essentially, you should probably be binding the click event specifically to your `a.box-picture` element instead of the entire `<figure>` element. Likely you can use the below:

Find this:
```javascript
var thumbElements = el.childNodes
```

Replace with this:
```javascript
var thumbElements = el.querySelectorAll('a.box-picture')
```

**Comment by Le-future** [comment]
I understand completely what you say, unfortunately, I made the changement you advised me but now, the gallery doesn't open and I get this error in the Chrome console : 

main.js:34 : Uncaught TypeError: Cannot read property 'split' of null

**Comment by mjau-mjau** [comment]
Ok, sorry I am not familiar with this non-jquery Photoswipe sample code that you are using to bind click events. Likely you would need to change a few other lines also, but sorry I don't have time to look into this right now ...

Ultimately, you need either A) Fix so that the click event is bound to `a.box-picture` instead of the entire figure, or B) Add an exception so that ancestor elements `A` inside `figcaption` are excluded from the click event.

**Comment by Le-future** [comment]
Ok I understand.

How could I run the gallery with an other method than this one? I have used the method explained in the documentation of PhotoSwipe actually.

Thanks!

**Comment by mjau-mjau** [comment]
Yes I know it's the method explained in the docs. Problem is, this specific code isn't very flexible if you want to target elements that are not direct children of your main gallery element ... unless you wish to customize the code, which requires spending some time with it. It's added like this, because it's assumed you have a given html structure, and because the author of PS doesn't want to assume that jQuery is available. I would have suggested a fix in the code, but as mentioned, Im not familiar with this specific code, and my vanilla JS is a bit rusty so I don't want to get started on a custom solution based on non-familiar code ...

Here is a solution from someone who basically ported the sample method to use jQuery:
https://gist.github.com/kshnurov/8b175b8798d4a907e47b

If you can get that working, I could easily add any further fixes. Would be tomorrow though ...

**Comment by Le-future** [comment]
Honestly I'm lost, my JS level is not good enough I guess 😞 

For me the best solution would be to exclude the a tags added inside the figcaption.

**Comment by mjau-mjau** [comment]
I'll give it a go tomorrow and test it on codepen ...

**Comment by Le-future** [comment]
You are just awesome, I'm still trying to find a solution on my side.

Have a good night 😉

**Comment by Le-future** [comment]
I found a solution!

I take example with a link like this in your figcaption :

<pre><a href="http://awesomewebsiteexample.com" target="_blank" class="external-link">External link</a></pre>

Add in my main.js file this :

<pre>$('.external-link').on( "click", function() {
        window.open(this.getAttribute('href'), '_blank');
        return false;
    });</pre>

Just below this :

<pre>// execute above function
    initPhotoSwipeFromDOM('.my-gallery');</pre>

**Comment by mjau-mjau** [comment]
I have a slightly better solution for you. After `initPhotoSwipeFromDOM('.my-gallery');`, just add the following. It will prevent Photoswipe from catching clicks on links in your figcaption:
```javascript
$('figcaption').on('click','a',function(e){
  e.stopPropagation();
});
```
Good work on your fix, but you should preferably avoid it because **A)** It opens the link with javascript instead of native browser **B)** It might get blocked as "popup" because of this and **C)** User cannot open the link with key-combo's such as `cmd+click` (open link in new tab). The solution above filters through normal behavior for the links, but simply prevents the event from bubbling up to Photoswipe.

**Comment by Le-future** [comment]
Indeed your solution is working as well 😃 

BTW, I've tried to open the link in a new tab, cmd+click with my solution and it's working.

Thanks a lot for your help, much appreciated!

**Comment by creativetags** [comment]
Old thread but [my answer here](https://stackoverflow.com/a/71601743/203915) might help anyone else still searching.
