### ISSUE TITLE
isDragging

### ISSUE THREAD

**Issue by stev0n** [dimsemenov/PhotoSwipe#1054]
Hi

pswp.isDragging()  returns true even if the mouse has up/down on the same spot, ie no drag movement.
shouldn't it return false until the slide has moved a certian distance ?

Is this a bug or is  there an example of how to prevent a slide mouse interaction if the slide is being dragged ?

I want the click or mouseup on the slide to fire only if the slide is not being dragged.
I want to prevent a mouseup/click on slide while dragging.

i've been experimenting with 'preventDragEvent' but i can't stop the mouseup being passed to the slide.

regards

steve

**Comment by dimsemenov** [comment]
I strongly don't recommend to listen for `mouseup` event.

You can bind `pswpTap` and `click` events to any element of PhotoSwipe, which aren't firing during drag. Check also this page http://photoswipe.com/documentation/custom-html-in-slides.html and option `isClickableElement `.

Regarding `isDragging` method, it's intentional behaviour, not a bug.

**Comment by stev0n** [comment]
ok,


i will look into your suggestions.


thanks


steve
