### ISSUE TITLE
Need to refresh to open gallery again

### ISSUE THREAD

**Issue by Shivang44** [dimsemenov/PhotoSwipe#1157]
Hi everyone. I am using the code from getting started as-is and then I have a simply jquery click event:
```

		$('#photolink').click((e) => 
			{
                                e.preventDefault();
				gallery2.init();
			});
```

It works fine, but when I close the gallery, and then click the link again, it doesn't work. No errors in chrome console. If I refresh and try again, it works. I've done a lot of searching and the only solution people have found is to add "rel=external" to the anchor, but this doesn't fix it for me.

**Comment by chesio** [comment]
Hi, you're not using the code from [getting started](http://photoswipe.com/documentation/getting-started.html) as-is, because you don't re-create the gallery object in your click handler:
<pre>
// Pass data to PhotoSwipe and initialize it
gallery = new PhotoSwipe(pswpElement, PhotoSwipeUI_Default, items, options);
gallery.init();
</pre>

**Comment by Shivang44** [comment]
I apologize, I didn't realize recreating the gallery object on each click was required. This issue can be closed.
