### ISSUE TITLE
How to make the bottombar as high as the available space under the image?

### ISSUE THREAD

**Issue by Jogai** [dimsemenov/PhotoSwipe#1206]
Currently its like this:

```
+--------------+
|     top      |
+--------------+

   +--------+
   |        |
   |  img   |
   |        |
   +--------+

+--------------+
|    caption   |
+--------------+

```

How can i achieve this:

```
+--------------+
|     top      |
+--------------+

   +--------+
   |        |
   |  img   |
   |        |
+--+--------+--+
|              |
|   caption    |
|              |
+--------------+

```

Or better yet:

```
+--------------+
|     top      |
+--------------+

   +--------+
   |        |
   |  img   |
   |        |
   +--------+
   |        |
   |caption |
   |        |
   +--------+
```

**Comment by tomdav999** [comment]
I make the top bar transparent (otherwise it feels obtrusive) and center the image vertically (raising it only as needed to prevent obscuring the caption or lowering if it bleeds into the controls).  You don't want to raise or lower the image too much or the arrows won't appear centered with the image.  The arrows need to remain in a fixed position for all images for user friendliness.  See my [test page](http://www.nwhikers.net/test.htm) (work in progress).  Happy to share the code if this is what you are looking for.

**Comment by Jogai** [comment]
I not only want to make the caption bigger, just that its taking the height there is so the text is directly below the image.

In your example with the panorama, the text is still at the bottom.

This would be the best:

```
+---------------+
|     top       |
+---------------+

   +---------+
   |         |
   |   img   |
   |         |
   +---------+
   | caption |
   +---------+

+---------------+
```

**Comment by tomdav999** [comment]
You would need to hide the caption while the image is being zoomed or panned and then dynamically reposition it.  Certainly doable but not that simple.

**Comment by tomdav999** [comment]
I was able to get this working and agree it looks better than docking the caption at the bottom of the page.  Also has as side benefit of freeing up screen real estate when the image is zoomed larger than the page.  Check out the sample.  Still need to tweak things to hide the caption when the user swipes left/right (otherwise it bleeds into the next image).

**Comment by tomdav999** [comment]
I noticed a bug in the original code.  Be sure to add the bolded item below to _positionCaption function:

		if (_initialZoomRunning || _mainScrollAnimating **|| !self.currItem.container**) {

**Comment by jhabdas** [comment]
@Jogai could you close this and reopen on StackOverflow if you're still having issues?
