### ISSUE TITLE
photoswipe 100% scaling (image only 1000 pixel high) is not sharp - images cropped and unsharp

### ISSUE THREAD

**Issue by PaddyPat** [dimsemenov/PhotoSwipe#1396]
hi,
thanks for your great plugin.

when viewing an image - my desktop resolution is much larger than 100% of the images but the images are reduced in fullscreen to 98/99%? So it's blurry and unsharp. (right image is sharp, left is "photoswipe fullscreen".

![uyeocovaqhcxus6dgiifhw](https://user-images.githubusercontent.com/11161270/28592766-52d61ee2-718a-11e7-8508-c0c20d5c446b.png)

any solution to fix it?

**Comment by dimsemenov** [comment]
Please link to the reduced test case, or at least to any page with the issue.

**Comment by PaddyPat** [comment]
example (this issue is at every image)
https://www.patsblog.de/2017/07/06/mit-dem-rennradl-von-oberstaufen-nach-immenstadt-sonthofen-bad-hindelang-oberjoch-jochpass-und-zurueck/

directlink image
https://www.patsblog.de/wordpress/wp-content/uploads/2017/07/20170706_103037.jpg

br
Pat

**Comment by dimsemenov** [comment]
Are you sure that you defined correct size in the array of slides with URLs and dimensions? Print your slides array in console. 

![image](https://user-images.githubusercontent.com/1061115/28606478-f04f9d60-71df-11e7-8744-c7442981b81f.png)

**Comment by xhoskin** [comment]
I confirm this bug. 
I noticed, that in [tutsplus tutorial ](http://tutsplus.github.io/photoswipe-jquery/) the pictures are crisp. They use v.4.0.6 of Photoswipe. When I revert from v.4.1.1 to v.4.0.8 the bug dissapears, pictures are crisp again.

As far as I understand, the problems begin in [this commit]((https://github.com/dimsemenov/PhotoSwipe/commit/8b4436f91a2889a3ebf6c87019496101f800508c)), where the `scale()` calculates

**Comment by xhoskin** [comment]
@PaddyPat images are not reduced in fullscreen to 98/99%
Webkit renders them unperfectly when they are in `transform: scale()`

**Comment by caseyjhol** [comment]
@dimsemenov You can see examples here:

v4.0.8 (working properly): https://plnkr.co/edit/Uehd9ZFaFTpAhDmjM4Qi?p=preview

![image](https://user-images.githubusercontent.com/2874325/45054516-77df6e00-b04a-11e8-8317-d2d791bdab62.png)

v4.1.1 (scaled incorrectly): https://plnkr.co/edit/VYbtuI1cK3SCCTIB5nEC?p=preview

![image](https://user-images.githubusercontent.com/2874325/45054524-7e6de580-b04a-11e8-9264-28f49ae4c5b4.png)

The code in both examples is identical with the only difference being the version of PhotoSwipe used.

To recreate:

1. Click the blue "Launch the preview in a separate window" button in the upper right corner of the preview window.
2. Click the first image.
3. Inspect with devtools.

You'll see that result of v4.1.1 is an image that is the same size (1000x667), but it's blurry because it has been scaled up to 1703x1136 and then scaled by 0.587199.

**Comment by NickBack** [comment]
@dimsemenov 
I'd really like this to be fixed as well.

Here are my findings.
1. It only happens on Webkit (Safari)
2. The reason is that the pswp__zoom-wrap div has (for some reason) a scale of less than 1.
3. Which make the image have width and height larger than it should.
4. Which makes Safari try to interpolate the image (since it thinks it's not at native res).

To recreate:
1. Open https://www.kickback-studios.com/media.html
2. Click any image.
3. Notice that image looks kinda blurry (compare with "Open image in new tab")
4. Look at source and notice that pswp__zoom-wrap has scale(0.7938257993384785) (or something like that)
5. And that the image has width and height higher than normal (it's so that the scale-in-zoomwrap*width = the-actual-width)

**Comment by caseyjhol** [comment]
In my previous example, starting when the window height is greater than 1124px, you'll see the issue (where the image is resized to be larger than its actual dimensions) and then scaled back down (so the effective dimensions are close to the image's dimensions). I'll need to look at the code more closely, but it seems like it'd make sense to simply not adjust the dimensions after a certain point. I've attached another example of this in effect (the effective dimensions of the image are 999.82x667 - they should be 1000x667). If there were no limit to the number of decimals allowed in a CSS transform, I don't think this would be an issue, but it looks like both Firefox and Chrome allow a maximum of 6 decimal places.

![image](https://user-images.githubusercontent.com/2874325/52538151-589ce900-2d2c-11e9-8397-79f2e6a7e55e.png)

**Comment by beejaz** [comment]
@caseyjhol Hi, would it be possible to get your PR or idea so I can implement by my self?

**Comment by dimsemenov** [comment]
fixed by v5.0
