### ISSUE TITLE
How to reset the gallery

### ISSUE THREAD

**Issue by andrienpecson** [dimsemenov/PhotoSwipe#1920]
How can I reset the gallery with a new set of images?

**Comment by dimsemenov** [comment]
There is no option to "reset", you initialize it again for the new element that you added and `destroy()` the old instance if it's no longer used. Alternatively, you may use `gallery` option from the parent element that is always present on the page.

For example, you may set `gallery` to the document root and then all `children` will be treated as slides. But this has a minor performance impact since PhotoSwipe will check every click.
