### ISSUE TITLE
The focusin event has been listened to, causing the copy function to be unavailable

### ISSUE THREAD

**Issue by wyy9630** [dimsemenov/PhotoSwipe#2015]
The webview in some APP will block the clipboard API, so I have to use the following method to reproduce. But focusin events will prevent me from selecting the text, preventing the copy operation.

```javascript
function clipboard (text) {
      var textarea = document.createElement('textarea')
      textarea.style.position = 'fixed'
      textarea.style.top = '10px'
      textarea.style.zIndex = '9999999'
      textarea.style.opacity = '0'
      textarea.value = text
      document.body.appendChild(textarea)
      textarea.select()
      document.execCommand('copy', true)
      document.body.removeChild(textarea)
}
```

**Comment by Eygle** [comment]
Same problem here.
We use the pswp only in part of the screen with a panel on the right containing texts and it's impossible de select the text from this panel).

Here you can see a demonstration of the problem :
![Peek 2023-09-12 16-45](https://github.com/dimsemenov/PhotoSwipe/assets/3872969/b3be09b5-d39b-445b-b865-3386f2b9aacd)

What I did is go to the demo website, select texts without problem, opened the pswp, reduce it's size using the chrome inspector tool and tried (unsuccessfully) to select the text. You can see that double or triple clic works but not the selection through mousedown + drag.

If you inject an iframe in the page, you can select inside the iframe, still not on the demo page which includes the pswp which is normal since the iframe has a different context (document, window, body, ...)

"Fun" fact: this is not a problem on Firefox, everything works great with it.

**Comment by dimsemenov** [comment]
@Eygle This is likely caused by `preventDefault` of the `pointermove` event. https://github.com/dimsemenov/PhotoSwipe/blob/master/src/js/gestures/gestures.js#L221 

There are several issues that appear if `preventDefault` isn't called: random selections of elements when the mouse is used,  page scroll/toolbars on mobile. PhotoSwipe is designed as a dialog, not as an inline carousel.

However, adding an API that would allow controlling when `preventDefault` is called might be a good idea.

The initial issue by @wyy9630 seems to be a different problem, related to the trapping of focus within the PhotoSwipe https://github.com/dimsemenov/PhotoSwipe/blob/master/src/js/keyboard.js#L156

**Comment by Eygle** [comment]
Hi @dimsemenov 
Thanks for your quick answer!

Indeed PhotoSwipe is designed as a dialog and we tweaked what it was made to do originally, it just is a very good tool for our needs _(Thanks for your work :+1:)_.

We use the lib since version 4 and still does in [another website](https://www.interencheres.com/recherche/lots) _(you can click on any lot and it will open the PhotoSwipe)_. In the version 4 the problem does not exist, we can select text in the additional panel we add on the right.

To avoid the text selection you can play with `user-select: none` CSS rule _(I'm aware you already know that since you use it already)_.
We also had scroll problem with our dialogs and we managed that by adding style on body to remove the scrollbar set by the content behind the dialog (`overflow: hidden`), saving the scroll position then removing the CSS rule on close then scrolling to the previous position.

I'm not sure this kind of workaround can apply here, I'll let you be the judge of that.

For our needs, the ability to configure the usage of `preventDefault` would be a great idea otherwise!

I'm sorry I misunderstood @wyy9630 original issue and thought wrongly it was linked to mine. Do you want me to open a new issue with what I wrote ?

**Comment by Eygle** [comment]
Your code works for us, thanks! :ok_hand: 
When do you think you'll publish it on npm (no rush, just so we know if we need to continue rolling back to v4 or just wait for it to be on the npm repo).

**Comment by dimsemenov** [comment]
5.4.1 should be live now

https://photoswipe.com/filters/#preventpointerevent

added `trapFocus` option as well: https://photoswipe.com/options/#trapfocus

**Comment by Eygle** [comment]
Thank you very much!
I never posted an issue that was resolve that quickly, it really was great!

**Comment by wyy9630** [comment]
@dimsemenov I just saw your reply message. Your code has been incredibly helpful to me. Thank you so much for your response.
