### ISSUE TITLE
EXIF auto-rotation

### ISSUE THREAD

**Issue by M0rtenB** [dimsemenov/PhotoSwipe#725]
I can see the issue has been raised before and marked as solved, but on my system I do experience the problem.

Images don't auto-orient when viewed with Photoswipe based on their EXIF-data.
This is true in Firefox, Chrome and Safari on my Mac. On iOS Safari however it DOES auto-orient.
Further, on all three browsers on my Mac the image is auto-oriented if rendered stand-alone by the browser (i.e. right click "view image", etc).

**Comment by dimsemenov** [comment]
This feature won't be added, as it requires reading binary data of the image which is a mess on frontend. Besides that, PhotoSwipe displays image before it's entirely loaded. 

Look for server-side solutions, or "fix" images locally before uploading them to the server.

http://stackoverflow.com/questions/19456036/detect-exif-orientation-and-rotate-image-using-imagemagick

**Comment by tphelps19** [comment]
@dimsemenov  Here is why this is a problem for us (and others I'd imagine).  All our photos get uploaded from iPhones, and on iPhones all the raw images are the same dimensions.  This makes for very smooth looking thumbnails.  My application that requires the thumbnails get constantly regenerated (because the source directory of images gets changed from computer clients as well as from the mobile app).  And if I do what you're suggesting and upon upload just use ImageMagick to save the original image in the proper orientation then every time the thumbnails have to be regenerated they no longer will all be the same dimensions.

I know it'd be a lot of work but this really would be a HUGE help to incorporate this into PS so we can properly view all images on iOS devices.

**Comment by caojianfeng** [comment]
May you give us a api that can set the rotation manual ？
now we can only push src w and h .
```
pswp.items.push({
    src: "path/to/image.jpg", 
    w:1200,
    h:500 
});
```
