### ISSUE TITLE
Loop option is not working

### ISSUE THREAD

**Issue by Gitupah** [dimsemenov/PhotoSwipe#733]
Hi. I added "loop: false" to the options in your codepen (http://codepen.io/play/pen/bNWRLK) but it didn't stop the gallery from looping.

**Comment by dimsemenov** [comment]
Please read the documentation on `loop` option http://photoswipe.com/documentation/options.html

It doesn't apply to arrows, if you want to hide first/last arrow, you'll need to hide them manually via gallery api.

**Comment by XavierDupessey** [comment]
I agree this behaviour is by design and a custom UI makes it possible to hide first / last arrow. But the user will still be able to loop using his keyboard (if arrowKeys set to true). As this code is part of core.js, I think this feature should be native, don't you?

In fact, maybe this code should be moved in UI part letting just "prev" and "next" functions in core.js
