### ISSUE TITLE
Vertical drag closing

### ISSUE THREAD

**Issue by v-yanchevsky** [dimsemenov/PhotoSwipe#801]
Is there a way to change vertical drag closing sensitivity? For example, if I need to close the view by slightly vertical movement (without using custom swipe events).

**Comment by dimsemenov** [comment]
No, only by modifying source https://github.com/dimsemenov/PhotoSwipe/blob/master/src/js/gestures.js#L568 . Can you please elaborate why do you need this? Don't you think that some user will accidentally close it?

**Comment by v-yanchevsky** [comment]
Users just don't want to drag an image so long.
By the way, I resolved this problem by editing [this constant](https://github.com/dimsemenov/PhotoSwipe/blob/master/src/js/gestures.js#L744) `0.6`.

**Comment by dimsemenov** [comment]
To which value would you recommend to change it?

**Comment by v-yanchevsky** [comment]
`0.85` is cool for us. But I think that it would be better to set it as an option, against hardcode.
I will send a small pull request soon, if you do not mind :grinning:

**Comment by flowgrow** [comment]
:+1:

**Comment by evilebottnawi** [comment]
@dimsemenov please create setting :+1:

**Comment by JcDenton86** [comment]
Hello, I am using photoswipe on a cordova application. So far so good! 
I agree that that this should be an option that can disable dragging too. This is useful if you have a gallery and have to click on the image to start the carousel (then it make sense to drag an image to close the carousel and go back to the gallery and it's nice too :) ), but if you show the carousel by default, dragging the image will result in a white screen (because there is nowhere to go back, I believe). Am I right?

**Comment by v-yanchevsky** [comment]
Did you [check](http://photoswipe.com/documentation/options.html) the `closeOnVerticalDrag` option?

**Comment by JcDenton86** [comment]
Oh! I went through the option list but I must have missed it..Thanks
