### ISSUE TITLE
Swipe (looped) navigation stops when there are two slides

### ISSUE THREAD

**Issue by andfinally** [dimsemenov/PhotoSwipe#821]
When you have two slides and navigate to the end of the series, swipe (on touch devices) or click and drag on desktops no longer works - you can't swipe through to the first slide. Clicking or tapping on the right arrow does work though. Any other number of items is fine!

Example Codepen http://codepen.io/andfinally/pen/LEwogJ

**Comment by dimsemenov** [comment]
It's by design. `loop` option is always `false` where there are less than 3 slides http://photoswipe.com/documentation/options.html 

As it requires cloning of slides, which PhotoSwipe doesn't do to save memory, and a few other issues related to possible dynamic content in slides. If for whatever reason you need to loop 2 slides, you can clone item in the slides array that you pass to PhotoSwipe constructor, so you'll have 3 slides in total, and rewrite the counter indicator so it displays correct total amount.

**Comment by andfinally** [comment]
I see! Thanks Dmitry.

**Comment by yys-0505** [comment]
workaround: 
gallery.listen('afterChange', function() {
	const counterEl: Element = document.querySelector('.pswp__counter')
    counterEl.innerHTML = (gallery.getCurrentIndex()%2+1) + gallery.options.indexIndicatorSep + gallery.options.getNumItemsFn()/2;
});
