### ISSUE TITLE
DoubleTap in Firefox on Windows 8 Touch not working properly

### ISSUE THREAD

**Issue by zerodburn** [dimsemenov/PhotoSwipe#888]
Hi,

Using your demo site I get the following behaviour on my machine (Acer Aspire S7-392 Windows 8.1 laptop with latest updates and browser versions).

In Firefox, as soon as I tap once on the screen the image starts to zoom in. If I double tap the zoom event fires for few ms then stops, this means the hide/show captions on tap doesn't work.

In Chrome, IE and Opera I can double tap and the image will zoom, but a single tap does not zoom in - it hides/shows caption and controls.

**Comment by dimsemenov** [comment]
Firefox does not support touch API on Windows desktop touch devices, quote from MDN:

> Note: As of Gecko 24.0, the touch events support introduced with Gecko 18.0 has been disabled on the desktop version of Firefox, as some popular sites including Google and Twitter are not working properly. Once the bug is fixed, the API will be enabled again. To enable it anyway, open about:config and set the dom.w3c_touch_events.enabled pref to 2. The mobile versions including Firefox for Android and Firefox OS are not affected by this change. Also, the API has been enabled on the Metro-style version of Firefox for Windows 8.

https://developer.mozilla.org/en-US/docs/Web/API/Touch_events#Gecko_notes

It seems that they also stopped development of Metro-style Firefox for Windows 8.

Basically, what they do is just fire `mouse` events instead of `touch`, no matter what kind of pointer is used. So PhotoSwipe can't do much here.
