### ISSUE TITLE
initPhotoSwipeFromDOM is not part of plugin?

### ISSUE THREAD

**Issue by sk29110** [dimsemenov/PhotoSwipe#913]
I was wondering why initPhotoSwipeFromDOM is not part of plugin. Without initPhotoSwipeFromDOM the plugin doesn't work so I was just curious.

**Comment by dimsemenov** [comment]
Not everyone has the same gallery structure and not everyone needs PhotoSwipe to be opened from the list of elements. http://codepen.io/dimsemenov/pen/gbadPv

**Comment by unicornist** [comment]
> Not everyone has the same gallery structure and not everyone needs PhotoSwipe to be opened from the list of elements. http://codepen.io/dimsemenov/pen/gbadPv

Yes you are right, but if you make it somehow easier to adopt PhotoSwipe for more junior developers it would surely make a great impact on its market dominance. Because there are no alternatives to it. Not even close with such perfection.
I am thinking of a jQuery plugin that uses PhotoSwipe internally.

**Comment by unicornist** [comment]
I came up with this: https://codepen.io/Unicornist/pen/NoxMZG
Still have to add the `photoswipeParseHash` and the `fromURL` parts.
