### ISSUE TITLE
Features: Fit window height/width, Original size, Zoom on mouse scroll

### ISSUE THREAD

**Issue by moldcraft** [dimsemenov/PhotoSwipe#950]
Is it possible to add the following features?

* [Zoom with mouse wheel](https://github.com/dimsemenov/PhotoSwipe/issues/897) *(important)*
* Display image in original size *(important)*
* Fit window height/width *(not important)*

*To not break the compatibility with current users, these features can be disabled by default.*

----

Currently I use [this plugin](http://sourcebox.io/0c46173511e62607719a1a84998727d1/html) to display and inspect screenshots made with [this extension](https://chrome.google.com/webstore/detail/staticshot-screenshot-cap/bbgoenllpdnfljjapjcababahphohncj?hl=en).
I really like the PhotoSwipe's design and how it works on mobile, and I wan't to switch to it.

**Comment by mjau-mjau** [comment]
Sorry I can't answer about mouse-wheel, but "display image in original size" is already available for the visitor when they click the "zoom" button.

"Fit window height/width" - Do you mean having an option to fit the image by width *or* height, instead of how it is now with the image fit by width *and* height? If one was to add such an option, depending on image aspect vs screen aspect, it would often mean parts of the image would be hidden.

**Comment by moldcraft** [comment]
> but "display image in original size" is already available for the visitor when they click the "zoom" button.

I thought it is just zoomed a little. But if the zoom means original, then its very good :thumbsup:

> it would often mean parts of the image would be hidden

Ok, then ignore the Fit feature.

----

Thank you

**Comment by nunoguerra** [comment]
Some tips to implement maxZoom to fit window height/width?
